//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETrade.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.PurchaseOrderDetail = new HashSet<PurchaseOrderDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BasketId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> ShipperId { get; set; }
        public Nullable<int> PurchaseOrderStatusId { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> ShipperPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Member Member { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual PurchaseOrderStatus PurchaseOrderStatus { get; set; }
        public virtual Shipper Shipper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
    }
}
